services:
  redis:
    image: redis:8.2
    container_name: redis
    command: ["redis-server", "--appendonly", "yes","--bind", "0.0.0.0","--protected-mode", "no"]
    restart: always

  interviewer_agent:
    build:
      context: .
    container_name: interviewer_agent
    env_file:
      - .env
    ports:
      - "80:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: always